

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "kip-sql"
version = "0.1.0"
edition = "2021"




[dependencies]
log = "^0.4"
sqlparser = "0.18.0"
thiserror = "1"
parking_lot = "0.12.1"
itertools = "0.10"

[dev-dependencies]
ctor = "0.2.0"
env_logger = "0.10"
paste = "^1.0"
rstest = "0.17"